### ISSUE TITLE
IS this project still active?

### ISSUE THREAD

**Issue by fidoboy** [OtaK/CMI8788Driver#1]
I'm very interested in this driver but i'm not sure if this project is still active. There is any news? I own a Asus Xonar DX and my OS is OSX 10.7.5 it could be really AMAZING to have this sound card running with Lion...

kind regards,

**Comment by OtaK** [comment]
I really don't have the time to update or continue this project, thus my decision to open-source what I have. I have some confidential docs also, and you can ask me to give those if necessary. (but I can't put them here, as it'd break the NDA)

I really need and want to end it up too, as my Xonar D1 is waiting being inactive for months now.

I'm really sorry about the HUGE delay this causes, but both professional life (as a now iOS engineer) and my personal life are too much time consuming to afford spending time on a project like this. (Yep, I'm talking about money, and whatever the donations and such, it'll never match what I earn by working, everyone needs to put food in the plate and have a roof to live under ;))

EDIT : BUT, I don't say that it's abandoned, I'll continue when I'll have the time :)

**Comment by kode54** [comment]
What about now? It's still missing the project files, by the way.

**Comment by OtaK** [comment]
Still no time for it, sorry.

What project files? You mean technical documents? They're under NDA, I can't give them out like that. I don't want to get sued ;)

**Comment by kode54** [comment]
No, I mean the Makefile, or the Xcode .xcodeproj folder. Unless you never got this into a buildable state yet.

**Comment by kode54** [comment]
I see you included the xcodeproj in your .gitignore. It would be nice if I could have the basic part of that project. Namely, the project.pbxproj, and maybe the project.xcworkspace. The xcuserdata folder is the only part of the xcodeproj that should have been excluded. :(

Also, hopefully I won't need the NDA documents, as I'll have the ALSA driver for reference.

EDIT: What the heck, I see you excluded that at some point, and with your last update two years ago, added the precompiled headers definition and strings plist to the gitignore file. Those are needed to compile it, and are not compiler generated, except at project creation time.

I guess I can try to make do without, as it doesn't look like it's ready to compile on its own yet anyway. It needs some serious work, I guess.
